jumble = list()
word1 = input("please insert a word\n")
word2 = input("please insert a word\n")
word3 = input("please insert a word\n")
word4 = input("please insert a word\n")
word5 = input("please insert a word\n")
jumble.append(word1)
jumble.append(word2)
jumble.append(word3)
jumble.append(word4)
jumble.append(word5)
print(jumble)
